### ISSUE TITLE
Component: Page Header

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#10]
# Stories

- As a reader of a guide, I want to know what section I'm in so that I know if I'm in the correct place.
- As a reader of a guide, I want to know what guide I'm in so that I know if I'm in the correct place.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [x] UX: Component design is drafted and shared for review
- [x] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

**Comment by jrubenoff** [comment]
### Status

I've committed an example to the `storybook` branch. Once #5 and #6 are done, I can open a PR with just this component for review.

Right now it looks like this:

<img width="995" alt="CleanShot 2023-06-15 at 07 51 41@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/89541cb9-22d4-457a-8440-c430dd8c5e12">

### Component API

I'm assuming we can specify the subhead and title in each file's front matter, e.g.:

```
---
subhead: Section 1
title: About the Playbook
---
```

### Note

The user stories above say the page header should let you know "what guide you're in." I've ignored that here because Site Navigation (#8) takes care of that.

**Comment by SMakaiTakori** [comment]
@jrubenoff This looks good to me!

**Comment by jeffmaher** [comment]
@admoorgit to review

**Comment by admoorgit** [comment]
@jrubenoff 
Let's ditch the all caps and switch to the darker green (#19825A) but otherwise this works for me!
