### ISSUE TITLE
Component: Site Footer

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#11]
# Stories

- As a reader of a guide, I want to know who created the guide so that I can learn more about who created the guide.
- As a reader of a guide, I want to be able to navigate to information about the guide's authoring org, so I can understand what experiences informed the guide's creation.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.edrxno737s72) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [ ] UX: Component design is drafted and shared for review
- [ ] Dev: Component design is reviewed and approved
- [ ] Peer UX: Compontent design is reviewed and approved
- [ ] Dev: Component style and markup is developed and shared for PR review
- [ ] Dev: Documentation on how to use component is drafted
- [ ] UX: Component style and markup is reviewed and approved
- [ ] Peer Dev: Component style and markup is reviewed and approved
- [ ] Component is available for use

**Comment by jrubenoff** [comment]
### Assumptions I'm making

It's OK to assume that only engineers will regularly edit the footer. So we can write it in HTML / YAML instead of Markdown.

### Design principles

[[As mentioned in Slack:](https://govbloomdigital.slack.com/archives/C01CYR2A21X/p1686248451524929)](https://govbloomdigital.slack.com/archives/C01CYR2A21X/p1686248451524929)

- Let visitors navigate to other pages without needing to scroll all the way back up
- Display the SBA certification at a legible size, so visitors understand what it means
- Visually separate multi-color images (e.g. the SBA logo) from monochrome icons for aesthetic reasons
- Remove any social media links that are no longer updated

### Visual design

Here's what I've come up with:

<img width="1359" alt="CleanShot 2023-06-14 at 10 16 48@2x" src="https://github.com/bloom-works/guides-template/assets/1328849/e6b471ff-15e8-4983-aea5-af8e1a11f101">

[Here's a responsive screencast.](https://govbloomdigital.slack.com/files/U059FD0Q2R3/F05BR8WG85S/footer-responsive.mp4)

### Status

I've committed an example to the `storybook` branch. Once #5 and #6 are done, I can open a PR with just the footer for review.

**Comment by SMakaiTakori** [comment]
@jrubenoff Great work! I agree that it's okay to have the footer written in HTML since it stays the same except for minimal changes. The way you have it set up looks good to me, the only thing that is a little hard to see is the `mail` icon. Maybe we fill it in so it's all white or make it a little bigger, thoughts @admoorgit ?

**Comment by jrubenoff** [comment]
@SMakaiTakori That is definitely a mistake on my end... the mail and LinkedIn icons should be the same size as the Bloom logo. Will fix when I create a branch.

**Comment by jeffmaher** [comment]
@jrubenoff has a PR up, ready for review by @SMakaiTakori  and @admoorgit
