### ISSUE TITLE
Styles: Typography

### ISSUE THREAD

**Issue by jeffmaher** [bloom-works/guides-template#12]
# Stories

- As a reader of a guide, I want to different kinds of text to appear different so that I can understand how the content is organized and follow it more easily.

# Notes

- See [the component doc](https://docs.google.com/document/d/1yC4y262CSiQ1iBqxjXPxFsOJJ1y0Z6WcDdnqY7sKnco/edit#heading=h.o18mksxm99io) for more information
- This ticket covers both design and development tasks. Change assignee of the ticket based on who has the next action, and remove the person or people that no longer have an action. It's expected that a ticket will get passed back and forth a few times.

# Done When

- [ ] UX: Design is drafted and shared for review
- [ ] Dev: Design is reviewed and approved
- [ ] Peer UX: Design is reviewed and approved
- [ ] Dev: Style is developed and shared for PR review
- [ ] UX: Style is reviewed and approved
- [ ] Peer Dev: Style and markup is reviewed and approved
- [ ] Style is available for use

**Comment by admoorgit** [comment]
Will get on this today or tomorrow @jrubenoff.  I will definitely have some tweaks, since the styles have diverged from the site and haven't been backfilled. STAY TUNED

**Comment by admoorgit** [comment]
Also — is there an instance I can access to review CSS directly? Or can you paste it here? Would prefer to give you updates in that format.

**Comment by jrubenoff** [comment]
Sure, here you go:

- [CSS variables](https://github.com/bloom-works/guides-template/blob/storybook/stories/scss/base/root.css#L2-L26)
- [Typography.css](https://github.com/bloom-works/guides-template/blob/storybook/stories/scss/base/typography.css)

`--t-paragraph` refers to the spacing between paragraphs.

Since I'm still waiting on #5 and #6 to open a PR here, you can give feedback by clicking on line numbers in the links aboce. That will give you anchor links you can reference them in a reply to this comment.

![CleanShot 2023-06-15 at 09 38 04@2x](https://github.com/bloom-works/guides-template/assets/1328849/fffb9447-0eea-4903-971f-d22dee37ace7)

**Comment by admoorgit** [comment]
Sorry for the delay — will get you specifics this week. We'll definitely bulk up H3 and get rid of all caps for readability though!

**Comment by jeffmaher** [comment]
Adam working on today/tomorrow.

**Comment by admoorgit** [comment]
see https://github.com/bloom-works/guides-template/pull/20
